### ISSUE TITLE
Improve Great Prophet

### ISSUE THREAD

**Issue by Caballero-Arepa** [DW8030/Better-Units-and-Natural-Wonders#1]
Often when I'm not interested on Religion, or I fail to make my own, I end up not creating my own religion. This results in me getting *useless* great prophets that can't do anything, they can't create a religion (as the max religions have been reached) and are of a patheon religion, so they can't spread anything.
The only use they could have is to make a Holy Site, but if you are not interested on religion or the foreign religion doesn't favour you to have faith, then its not worth it.

So, what I propose is to make Great Prophets be able to start a Golden Age, so at least they of more use.

**Comment by EmperorPinguin** [comment]
Good idea, I'll look at it.

**Comment by EmperorPinguin** [comment]
You have to keep in mind that it becomes very attractive to declare war on nations that try to convert your cities with Great Prophets.
